Text file: words_data.js
Latest content with line numbers:
1	// База данных слов по уровням английского языка
2	const wordsDatabase = {
3	  "A1": [
4	    { word: "hello", translation: "привет", category: "greetings" },
5	    { word: "goodbye", translation: "до свидания", category: "greetings" },
6	    { word: "please", translation: "пожалуйста", category: "politeness" },
7	    { word: "thank", translation: "благодарить", category: "politeness" },
8	    { word: "yes", translation: "да", category: "basic" },
9	    { word: "no", translation: "нет", category: "basic" },
10	    { word: "water", translation: "вода", category: "food" },
11	    { word: "food", translation: "еда", category: "food" },
12	    { word: "house", translation: "дом", category: "places" },
13	    { word: "family", translation: "семья", category: "people" },
14	    { word: "friend", translation: "друг", category: "people" },
15	    { word: "work", translation: "работа", category: "activities" },
16	    { word: "school", translation: "школа", category: "places" },
17	    { word: "book", translation: "книга", category: "objects" },
18	    { word: "car", translation: "машина", category: "transport" },
19	    { word: "time", translation: "время", category: "abstract" },
20	    { word: "day", translation: "день", category: "time" },
21	    { word: "night", translation: "ночь", category: "time" },
22	    { word: "good", translation: "хороший", category: "adjectives" },
23	    { word: "bad", translation: "плохой", category: "adjectives" }
24	  ],
25	  "A2": [
26	    { word: "beautiful", translation: "красивый", category: "adjectives" },
27	    { word: "important", translation: "важный", category: "adjectives" },
28	    { word: "different", translation: "разный", category: "adjectives" },
29	    { word: "interesting", translation: "интересный", category: "adjectives" },
30	    { word: "difficult", translation: "трудный", category: "adjectives" },
31	    { word: "possible", translation: "возможный", category: "adjectives" },
32	    { word: "necessary", translation: "необходимый", category: "adjectives" },
33	    { word: "available", translation: "доступный", category: "adjectives" },
34	    { word: "comfortable", translation: "удобный", category: "adjectives" },
35	    { word: "expensive", translation: "дорогой", category: "adjectives" },
36	    { word: "cheap", translation: "дешевый", category: "adjectives" },
37	    { word: "dangerous", translation: "опасный", category: "adjectives" },
38	    { word: "safe", translation: "безопасный", category: "adjectives" },
39	    { word: "healthy", translation: "здоровый", category: "adjectives" },
40	    { word: "sick", translation: "больной", category: "adjectives" },
41	    { word: "happy", translation: "счастливый", category: "emotions" },
42	    { word: "sad", translation: "грустный", category: "emotions" },
43	    { word: "angry", translation: "злой", category: "emotions" },
44	    { word: "tired", translation: "уставший", category: "emotions" },
45	    { word: "excited", translation: "взволнованный", category: "emotions" }
46	  ],
47	  "B1": [
48	    { word: "achievement", translation: "достижение", category: "abstract" },
49	    { word: "advantage", translation: "преимущество", category: "abstract" },
50	    { word: "adventure", translation: "приключение", category: "abstract" },
51	    { word: "agreement", translation: "соглашение", category: "abstract" },
52	    { word: "appearance", translation: "внешность", category: "abstract" },
53	    { word: "appointment", translation: "назначение", category: "abstract" },
54	    { word: "approach", translation: "подход", category: "abstract" },
55	    { word: "argument", translation: "аргумент", category: "abstract" },
56	    { word: "arrangement", translation: "договоренность", category: "abstract" },
57	    { word: "atmosphere", translation: "атмосфера", category: "abstract" },
58	    { word: "attitude", translation: "отношение", category: "abstract" },
59	    { word: "audience", translation: "аудитория", category: "people" },
60	    { word: "background", translation: "фон, происхождение", category: "abstract" },
61	    { word: "balance", translation: "баланс", category: "abstract" },
62	    { word: "behavior", translation: "поведение", category: "abstract" },
63	    { word: "benefit", translation: "польза", category: "abstract" },
64	    { word: "budget", translation: "бюджет", category: "money" },
65	    { word: "challenge", translation: "вызов", category: "abstract" },
66	    { word: "character", translation: "характер", category: "abstract" },
67	    { word: "choice", translation: "выбор", category: "abstract" }
68	  ],
69	  "B2": [
70	    { word: "accomplish", translation: "выполнять", category: "verbs" },
71	    { word: "acknowledge", translation: "признавать", category: "verbs" },
72	    { word: "acquire", translation: "приобретать", category: "verbs" },
73	    { word: "adapt", translation: "адаптироваться", category: "verbs" },
74	    { word: "adequate", translation: "адекватный", category: "adjectives" },
75	    { word: "advocate", translation: "защищать", category: "verbs" },
76	    { word: "alternative", translation: "альтернатива", category: "abstract" },
77	    { word: "analyze", translation: "анализировать", category: "verbs" },
78	    { word: "anticipate", translation: "предвидеть", category: "verbs" },
79	    { word: "apparent", translation: "очевидный", category: "adjectives" },
80	    { word: "appreciate", translation: "ценить", category: "verbs" },
81	    { word: "appropriate", translation: "подходящий", category: "adjectives" },
82	    { word: "approximate", translation: "приблизительный", category: "adjectives" },
83	    { word: "arbitrary", translation: "произвольный", category: "adjectives" },
84	    { word: "aspect", translation: "аспект", category: "abstract" },
85	    { word: "assess", translation: "оценивать", category: "verbs" },
86	    { word: "assume", translation: "предполагать", category: "verbs" },
87	    { word: "assure", translation: "уверять", category: "verbs" },
88	    { word: "attach", translation: "прикреплять", category: "verbs" },
89	    { word: "attribute", translation: "приписывать", category: "verbs" }
90	  ],
91	  "C1": [
92	    { word: "abstract", translation: "абстрактный", category: "adjectives" },
93	    { word: "abundant", translation: "изобильный", category: "adjectives" },
94	    { word: "accelerate", translation: "ускорять", category: "verbs" },
95	    { word: "accommodate", translation: "размещать", category: "verbs" },
96	    { word: "accumulate", translation: "накапливать", category: "verbs" },
97	    { word: "accurate", translation: "точный", category: "adjectives" },
98	    { word: "adjacent", translation: "смежный", category: "adjectives" },
99	    { word: "advocate", translation: "сторонник", category: "nouns" },
100	    { word: "aesthetic", translation: "эстетический", category: "adjectives" },
101	    { word: "aggregate", translation: "совокупность", category: "nouns" },
102	    { word: "allocate", translation: "распределять", category: "verbs" },
103	    { word: "ambiguous", translation: "двусмысленный", category: "adjectives" },
104	    { word: "analogous", translation: "аналогичный", category: "adjectives" },
105	    { word: "anticipate", translation: "предвосхищать", category: "verbs" },
106	    { word: "arbitrary", translation: "произвольный", category: "adjectives" },
107	    { word: "articulate", translation: "четко выражать", category: "verbs" },
108	    { word: "assimilate", translation: "усваивать", category: "verbs" },
109	    { word: "attribute", translation: "свойство", category: "nouns" },
110	    { word: "autonomous", translation: "автономный", category: "adjectives" },
111	    { word: "coherent", translation: "связный", category: "adjectives" }
112	  ],
113	  "C2": [
114	    { word: "aberration", translation: "отклонение", category: "nouns" },
115	    { word: "abstruse", translation: "непонятный", category: "adjectives" },
116	    { word: "accentuate", translation: "подчеркивать", category: "verbs" },
117	    { word: "acquiesce", translation: "молчаливо соглашаться", category: "verbs" },
118	    { word: "admonish", translation: "предостерегать", category: "verbs" },
119	    { word: "aesthetic", translation: "эстетика", category: "nouns" },
120	    { word: "alleviate", translation: "облегчать", category: "verbs" },
121	    { word: "amalgamate", translation: "объединять", category: "verbs" },
122	    { word: "ambivalent", translation: "двойственный", category: "adjectives" },
123	    { word: "ameliorate", translation: "улучшать", category: "verbs" },
124	    { word: "anachronism", translation: "анахронизм", category: "nouns" },
125	    { word: "analogous", translation: "аналогичный", category: "adjectives" },
126	    { word: "anecdotal", translation: "основанный на слухах", category: "adjectives" },
127	    { word: "anomaly", translation: "аномалия", category: "nouns" },
128	    { word: "antipathy", translation: "антипатия", category: "nouns" },
129	    { word: "apathy", translation: "апатия", category: "nouns" },
130	    { word: "apprehensive", translation: "опасающийся", category: "adjectives" },
131	    { word: "arbitrary", translation: "произвольный", category: "adjectives" },
132	    { word: "archaic", translation: "архаичный", category: "adjectives" },
133	    { word: "articulate", translation: "красноречивый", category: "adjectives" }
134	  ]
135	};
136	
137	// Экспорт для использования в приложении
138	if (typeof module !== 'undefined' && module.exports) {
139	  module.exports = wordsDatabase;
140	}
141	
142	